kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql-storage
  namespace: mysql-cluster
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: mysql-cluster
  labels:
    type: local
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-2
  namespace: mysql-cluster
  labels:
    type: local
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-3
  namespace: mysql-cluster
  labels:
    type: local
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"